@istest
public with sharing class LeadExtensiontest1234 {

 static testmethod void LeadExtensiontest (){ 
 
   /*     Lead testLead = new Lead();
         testlead.status = 'New';
         testlead.Channel__c ='RB Portal';
         testlead.Channel_Sources__c = 'Bank';
         testlead.firstname = 'test';
         testlead.lastname = 'lead1';
         testlead.Company = 'Test';        
         testlead.Is_Sofi_Lead__c = true;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.Transfer_To_HLR__c = true;
         testlead.RecordTypeId = [select Id from RecordType where Name Like: 'No_Send_to_empower' and SobjectType = 'Lead'].Id;         
         insert testlead;

         ApexPages.StandardController sc1 = new ApexPages.StandardController(testLead);
         LeadExtension ctr1 = new LeadExtension(sc1);         
         PageReference ref1= page.LeadDetail;
         ref1.getParameters().put('id', String.valueOf(testLead.Id));
         Test.setCurrentPage(ref1);
         ctr1.init();
         
         
         
         Lead testLead1 = new Lead();
         testlead1.status = 'New';
         testlead1.Channel__c ='RB Portal';
         testlead1.Channel_Sources__c = 'Bank';
         testlead1.firstname = 'test';
         testlead1.lastname = 'lead2';
         testlead1.Company = 'Test';        
         //testlead1.Is_Sofi_Lead__c = true;
         testlead1.Property_State__c = 'TX';
         testlead1.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead1.Transfer_To_HLR__c = true;
         testlead1.Empower_Lead_ID__c = 'D1001390';
         //testlead1.RecordTypeId = [select Id from RecordType where Name Like: 'No_Send_to_empower' and SobjectType = 'Lead'].Id;         
         insert testlead1;
         
         ApexPages.StandardController sc2 = new ApexPages.StandardController(testLead1);
         LeadExtension ctr2 = new LeadExtension(sc2);         
         PageReference ref2= page.LeadDetail;
         ref2.getParameters().put('id', String.valueOf(testLead.Id));
         Test.setCurrentPage(ref2);
         ctr2.init();
        
    */     
         
}
}